In [1]:
import numpy as np

# Numpy Array

In [2]:
myList = [20,30,40]

In [3]:
type(myList)

list

In [7]:
np.array(myList)

array([20, 30, 40])

In [8]:
matrixList = [[10,20,30],[20,30,40],[30,40,50]]

In [9]:
matrixList[1][0]

20

In [10]:
np.array(matrixList)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

# arange

In [18]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

# zeros

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [29]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

# linspace

In [30]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [31]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

# eye

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# random

In [35]:
np.random.randn(8)

array([-0.97551699, -1.175904  , -1.1199822 , -0.94957897, -1.44147335,
       -1.75756772, -0.37792829, -0.34735526])

In [36]:
np.random.randn(4,4)

array([[ 0.34417637,  1.53306232, -0.15219652,  0.12664393],
       [-1.13478652,  1.47569515,  0.97190574, -0.0352241 ],
       [ 1.41849955,  0.25994109, -0.84541112, -0.95640755],
       [-0.60883938,  0.38090299,  0.94558512,  1.27742013]])

In [42]:
np.random.randint(1,10)

4

In [46]:
np.random.randint(0,210,5)

array([ 87,  80,  52, 203, 173])

In [51]:
myNumpyArray = np.arange(30)

In [52]:
myNumpyArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [56]:
myRandomArray = np.random.randint(0,100,20)

In [57]:
myRandomArray

array([18, 21, 42, 43, 68,  3, 81,  4,  8, 56, 96, 77,  3, 55, 10, 71, 72,
       41, 86, 84])

# numpy dizi methodları

In [60]:
myNumpyArray.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [62]:
myNumpyArray.max()

29

In [66]:
myRandomArray.max()

96

In [67]:
myRandomArray.argmax()

10

In [68]:
myRandomArray.argmin()

5

In [74]:
reshapeArray = myNumpyArray.reshape(5,6)

In [75]:
reshapeArray.shape

(5, 6)