In [1]:
import numpy as np

In [2]:
myArray = np.arange(0,15)

In [3]:
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
myArray[5]

5

In [5]:
myArray[3:8]

array([3, 4, 5, 6, 7])

In [6]:
myArray[3:8] = -5

In [7]:
myArray

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [8]:
anyArray = np.arange(0,24)

In [9]:
anyArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [15]:
slicingArray = anyArray[4:9]

In [16]:
slicingArray

array([4, 5, 6, 7, 8])

In [17]:
anyArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [18]:
slicingArray[:] = 700

In [19]:
slicingArray

array([700, 700, 700, 700, 700])

In [20]:
anyArray

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [21]:
exampleArray = np.arange(0,24)

In [22]:
exampleArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [24]:
exampleArrayCopy = exampleArray.copy()

In [25]:
exampleArrayCopy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [26]:
exampleArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [34]:
exampleArrayCopySlicing = exampleArrayCopy[3:6]

In [36]:
exampleArrayCopySlicing[:] = 80

In [37]:
exampleArrayCopySlicing

array([80, 80, 80])

In [38]:
exampleArrayCopy

array([ 0,  1,  2, 80, 80, 80,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [39]:
exampleArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [40]:
#Eğer bir dizi içersinde işlemler yapıyorsak diğer dizinin değişmemesi için kopyasını çağırıp üzerinden işlemler yapabiliriz

# matrix

In [41]:
myList = [[10,20,30],[20,30,40],[40,50,60]]

In [42]:
matrixArray = np.array(myList)

In [46]:
matrixArray

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [47]:
matrixArray[0]

array([10, 20, 30])

In [48]:
matrixArray[1][2]

40

In [49]:
matrixArray[1,2]

40

In [63]:
matrixArray[2:,1:]

array([[50, 60]])

In [64]:
newList = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [65]:
newMatrix = np.array(newList)

In [66]:
newMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [68]:
newMatrix[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

# operasyonlar

In [71]:
newArray = np.random.randint(1,100,20)

In [72]:
newArray

array([ 3, 89, 59, 65, 76, 31,  1, 58, 47, 85, 20, 36, 33, 62, 37, 39, 11,
       75, 10,  3])

In [73]:
newArray > 24

array([False,  True,  True,  True,  True,  True, False,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
       False, False])

In [74]:
resultArray = newArray > 24

In [75]:
resultArray

array([False,  True,  True,  True,  True,  True, False,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
       False, False])

In [76]:
newArray

array([ 3, 89, 59, 65, 76, 31,  1, 58, 47, 85, 20, 36, 33, 62, 37, 39, 11,
       75, 10,  3])

In [77]:
newArray[resultArray]

array([89, 59, 65, 76, 31, 58, 47, 85, 36, 33, 62, 37, 39, 75])

In [78]:
newArray

array([ 3, 89, 59, 65, 76, 31,  1, 58, 47, 85, 20, 36, 33, 62, 37, 39, 11,
       75, 10,  3])

In [79]:
newArray[newArray > 24]

array([89, 59, 65, 76, 31, 58, 47, 85, 36, 33, 62, 37, 39, 75])

In [80]:
endArray = np.arange(0,24)

In [81]:
endArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [82]:
endArray + endArray

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [83]:
endArray * endArray

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [84]:
endArray - endArray

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [85]:
endArray / endArray

<ipython-input-85-9a854cacbf13>:1: RuntimeWarning: invalid value encountered in true_divide
  endArray / endArray


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [86]:
np.sqrt(endArray)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [88]:
np.max(endArray)


23

In [89]:
np.min(endArray)

0